
services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    networks:
      - exploitnet

  ldap:
    build: ./ldap
    ports:
      - "1389:1389"
    networks:
      - exploitnet
  
networks:
  exploitnet:
