services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    env_file: .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    restart: on-failure:5
    security_opt:
      - apparmor=docker-default
      - label=type:container_t
    deploy:
      resources:
        limits:
          memory: 512M
          pids: 300
          cpus: "1.0"
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./certs/server.crt:/etc/nginx/conf/server.crt:ro
      - ./certs/server.key:/etc/nginx/conf/server.key:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dmz
      - internal
      
  flaskapp:
    build: ./flaskapp
    env_file: .env
    environment:
      - KEYCLOAK_URL
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
    depends_on:
      - keycloak
    restart: on-failure:5
    command: ["python", "app.py"]
    read_only: true
    security_opt:
      - apparmor=docker-default
      - label=type:container_t
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    deploy:
      resources:
        limits:
          memory: 200M
          pids: 100
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    volumes:
      - ./certs:/app/certs:ro

  waf:
    image: owasp/modsecurity-crs:nginx
    restart: on-failure:5
    ports:
      - "15000:443"
    volumes:
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    depends_on:
      - flaskapp
    command: ["nginx", "-g", "daemon off;"]
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp
    security_opt:
      - apparmor=docker-default
      - label=type:container_t
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
          pids: 100
    networks:
      - dmz
      - internal
       
volumes:
  keycloak-data:
  
networks:
  dmz:
  internal:
    internal: true

