services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    env_file: .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    restart: on-failure:5
    security_opt:
      - label=type:container_t
    cpu_quota: 100000
    cpu_period: 100000
    deploy:
      resources:
        limits:
          memory: 512M
          pids: 300
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/demo-realm"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 90s
    networks:
      - dmz
      - internal
      
  flaskapp:
    build: ./flaskapp
    env_file: .env
    environment:
      - KEYCLOAK_URL
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
    depends_on:
      - keycloak
    restart: on-failure:5
    command: ["python", "app.py"]
    read_only: true
    security_opt:
      - label=type:container_t
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    cpu_quota: 50000
    cpu_period: 100000
    deploy:
      resources:
        limits:
          memory: 200M
          pids: 100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "15000:80"
    volumes:
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
    depends_on:
      - flaskapp
    command: ["nginx", "-g", "daemon off;"]
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp
    security_opt:
      - label=type:container_t
      - no-new-privileges:true
    cpu_quota: 50000
    cpu_period: 100000
    deploy:
      resources:
        limits:
          memory: 200M
          pids: 100
    networks:
      - dmz
      - internal
       
volumes:
  keycloak-data:

networks:
  dmz:
  internal:
    internal: true
